package dev.garnetforge.app.root

import android.content.Context
import com.topjohnwu.superuser.Shell
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Manages copying bundled shell scripts from APK assets → /data/adb/garnetforge/
 * and running detect_nodes.sh on first install or after update.
 *
 * Directory structure:
 *   /data/adb/garnetforge/
 *     apply.sh          ← from assets/scripts/
 *     set_cfg.sh        ← from assets/scripts/
 *     detect_nodes.sh   ← from assets/scripts/
 *     config.prop       ← default from assets/scripts/ (only on first install)
 *     nodes.prop        ← generated by detect_nodes.sh
 *     garnetforge.log
 *     thermal_apps.prop
 */
object ScriptManager {

    const val INSTALL_DIR = "/data/adb/garnetforge"
    private val SCRIPTS   = listOf("apply.sh", "set_cfg.sh", "detect_nodes.sh")
    private val VERSION_FILE = "$INSTALL_DIR/.app_version"

    /** Returns true if scripts are up-to-date. Installs/updates otherwise. */
    suspend fun ensureInstalled(ctx: Context, appVersionCode: Int): Boolean =
        withContext(Dispatchers.IO) {
            runCatching {
                // Create directory
                Shell.cmd("mkdir -p $INSTALL_DIR").exec()

                // Check installed version
                val installedVersion = Shell.cmd("cat $VERSION_FILE 2>/dev/null")
                    .exec().out.firstOrNull()?.trim()?.toIntOrNull() ?: 0

                val needsUpdate = installedVersion < appVersionCode
                val nodesExist  = Shell.cmd("[ -f $INSTALL_DIR/nodes.prop ] && echo y")
                    .exec().out.firstOrNull() == "y"

                // Copy scripts from assets
                SCRIPTS.forEach { script ->
                    copyAsset(ctx, "scripts/$script", "$INSTALL_DIR/$script")
                    Shell.cmd("chmod 755 $INSTALL_DIR/$script").exec()
                }

                // Copy default config.prop only if it doesn't exist yet
                val configExists = Shell.cmd("[ -f $INSTALL_DIR/config.prop ] && echo y")
                    .exec().out.firstOrNull() == "y"
                if (!configExists) {
                    copyAsset(ctx, "scripts/config.prop", "$INSTALL_DIR/config.prop")
                }

                // Run detect_nodes on first install or if nodes.prop missing
                if (!nodesExist || needsUpdate) {
                    Shell.cmd("sh $INSTALL_DIR/detect_nodes.sh").exec()
                }

                // Save version
                Shell.cmd("printf '%s' '$appVersionCode' > $VERSION_FILE").exec()

                true
            }.getOrDefault(false)
        }

    private fun copyAsset(ctx: Context, assetPath: String, destPath: String) {
        ctx.assets.open(assetPath).use { input ->
            val bytes = input.readBytes()
            // Write via shell to avoid permission issues with Java file API
            val b64 = android.util.Base64.encodeToString(bytes, android.util.Base64.NO_WRAP)
            Shell.cmd("printf '%s' '$b64' | base64 -d > $destPath 2>/dev/null").exec()
        }
    }

    fun isInstalled(): Boolean =
        Shell.cmd("[ -f $INSTALL_DIR/apply.sh ] && [ -f $INSTALL_DIR/config.prop ] && echo y")
            .exec().out.firstOrNull() == "y"
}
